distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 1.0.2
install_time: "Sun Nov 10 00:20:41 2024"
installation_id: "865f132a-b780-4038-b2f7-16b985a178b2"
rime_version: 1.11.2